# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jhelison\Documents\Python\PYQT\Gerenciador de boletos\Modelos\u_MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1294, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_notas_fiscais = QtWidgets.QWidget()
        self.tab_notas_fiscais.setObjectName("tab_notas_fiscais")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_notas_fiscais)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.tab_notas_fiscais)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(self.horizontalGroupBox_2)
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.comboBox_nf_filtro_colunas = QtWidgets.QComboBox(self.horizontalGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_nf_filtro_colunas.sizePolicy().hasHeightForWidth())
        self.comboBox_nf_filtro_colunas.setSizePolicy(sizePolicy)
        self.comboBox_nf_filtro_colunas.setObjectName("comboBox_nf_filtro_colunas")
        self.verticalLayout_9.addWidget(self.comboBox_nf_filtro_colunas)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.horizontalGroupBox_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.lineEdit_nf_filtro_text = QtWidgets.QLineEdit(self.horizontalGroupBox_3)
        self.lineEdit_nf_filtro_text.setObjectName("lineEdit_nf_filtro_text")
        self.verticalLayout_10.addWidget(self.lineEdit_nf_filtro_text)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.horizontalLayout_5.addWidget(self.horizontalGroupBox_3)
        self.horizontalGroupBox_4 = QtWidgets.QGroupBox(self.horizontalGroupBox_2)
        self.horizontalGroupBox_4.setObjectName("horizontalGroupBox_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.horizontalGroupBox_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_16.addWidget(self.label_14)
        self.comboBox_nfe_data_coluna = QtWidgets.QComboBox(self.horizontalGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_nfe_data_coluna.sizePolicy().hasHeightForWidth())
        self.comboBox_nfe_data_coluna.setSizePolicy(sizePolicy)
        self.comboBox_nfe_data_coluna.setObjectName("comboBox_nfe_data_coluna")
        self.verticalLayout_16.addWidget(self.comboBox_nfe_data_coluna)
        self.horizontalLayout_7.addLayout(self.verticalLayout_16)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.horizontalGroupBox_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.dateEdit_NF_inicial = QtWidgets.QDateEdit(self.horizontalGroupBox_4)
        self.dateEdit_NF_inicial.setCalendarPopup(True)
        self.dateEdit_NF_inicial.setObjectName("dateEdit_NF_inicial")
        self.verticalLayout_11.addWidget(self.dateEdit_NF_inicial)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.horizontalGroupBox_4)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.comboBox_nfe_pre_dates = QtWidgets.QComboBox(self.horizontalGroupBox_4)
        self.comboBox_nfe_pre_dates.setObjectName("comboBox_nfe_pre_dates")
        self.verticalLayout_12.addWidget(self.comboBox_nfe_pre_dates)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.horizontalGroupBox_4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.dateEdit_NF_final = QtWidgets.QDateEdit(self.horizontalGroupBox_4)
        self.dateEdit_NF_final.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_NF_final.setCalendarPopup(True)
        self.dateEdit_NF_final.setObjectName("dateEdit_NF_final")
        self.verticalLayout_13.addWidget(self.dateEdit_NF_final)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.horizontalLayout_5.addWidget(self.horizontalGroupBox_4)
        self.pushButton_nf_limpar_filtro = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.pushButton_nf_limpar_filtro.setObjectName("pushButton_nf_limpar_filtro")
        self.horizontalLayout_5.addWidget(self.pushButton_nf_limpar_filtro)
        self.verticalLayout_14.addWidget(self.horizontalGroupBox_2)
        self.tableWidget_NF = QtWidgets.QTableWidget(self.tab_notas_fiscais)
        self.tableWidget_NF.setAlternatingRowColors(True)
        self.tableWidget_NF.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_NF.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_NF.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_NF.setObjectName("tableWidget_NF")
        self.tableWidget_NF.setColumnCount(0)
        self.tableWidget_NF.setRowCount(0)
        self.verticalLayout_14.addWidget(self.tableWidget_NF)
        self.tabWidget.addTab(self.tab_notas_fiscais, "")
        self.tab_duplicatas = QtWidgets.QWidget()
        self.tab_duplicatas.setObjectName("tab_duplicatas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_duplicatas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.tab_duplicatas)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalGroupBox1 = QtWidgets.QGroupBox(self.horizontalGroupBox)
        self.horizontalGroupBox1.setObjectName("horizontalGroupBox1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalGroupBox1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox_duplicata_colunas = QtWidgets.QComboBox(self.horizontalGroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_duplicata_colunas.sizePolicy().hasHeightForWidth())
        self.comboBox_duplicata_colunas.setSizePolicy(sizePolicy)
        self.comboBox_duplicata_colunas.setObjectName("comboBox_duplicata_colunas")
        self.verticalLayout_2.addWidget(self.comboBox_duplicata_colunas)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalGroupBox1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_duplicatas_filtro_text = QtWidgets.QLineEdit(self.horizontalGroupBox1)
        self.lineEdit_duplicatas_filtro_text.setObjectName("lineEdit_duplicatas_filtro_text")
        self.verticalLayout_3.addWidget(self.lineEdit_duplicatas_filtro_text)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.horizontalGroupBox1)
        self.horizontalGroupBox2 = QtWidgets.QGroupBox(self.horizontalGroupBox)
        self.horizontalGroupBox2.setObjectName("horizontalGroupBox2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalGroupBox2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.horizontalGroupBox2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.comboBox_duplicata_data_coluna = QtWidgets.QComboBox(self.horizontalGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_duplicata_data_coluna.sizePolicy().hasHeightForWidth())
        self.comboBox_duplicata_data_coluna.setSizePolicy(sizePolicy)
        self.comboBox_duplicata_data_coluna.setObjectName("comboBox_duplicata_data_coluna")
        self.verticalLayout_15.addWidget(self.comboBox_duplicata_data_coluna)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.horizontalGroupBox2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.dateEdit_duplicata_inicial = QtWidgets.QDateEdit(self.horizontalGroupBox2)
        self.dateEdit_duplicata_inicial.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_duplicata_inicial.setProperty("showGroupSeparator", False)
        self.dateEdit_duplicata_inicial.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_duplicata_inicial.setCalendarPopup(True)
        self.dateEdit_duplicata_inicial.setObjectName("dateEdit_duplicata_inicial")
        self.verticalLayout_6.addWidget(self.dateEdit_duplicata_inicial)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.horizontalGroupBox2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.comboBox_duplicatas_pre_dates = QtWidgets.QComboBox(self.horizontalGroupBox2)
        self.comboBox_duplicatas_pre_dates.setObjectName("comboBox_duplicatas_pre_dates")
        self.verticalLayout_8.addWidget(self.comboBox_duplicatas_pre_dates)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.horizontalGroupBox2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.dateEdit_duplicata_final = QtWidgets.QDateEdit(self.horizontalGroupBox2)
        self.dateEdit_duplicata_final.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEdit_duplicata_final.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit_duplicata_final.setCalendarPopup(True)
        self.dateEdit_duplicata_final.setObjectName("dateEdit_duplicata_final")
        self.verticalLayout_7.addWidget(self.dateEdit_duplicata_final)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.horizontalLayout.addWidget(self.horizontalGroupBox2)
        self.pushButton_duplicata_limpar_filtro = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.pushButton_duplicata_limpar_filtro.setObjectName("pushButton_duplicata_limpar_filtro")
        self.horizontalLayout.addWidget(self.pushButton_duplicata_limpar_filtro)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.tableWidget_duplicata = QtWidgets.QTableWidget(self.tab_duplicatas)
        self.tableWidget_duplicata.setAlternatingRowColors(True)
        self.tableWidget_duplicata.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_duplicata.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_duplicata.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_duplicata.setObjectName("tableWidget_duplicata")
        self.tableWidget_duplicata.setColumnCount(0)
        self.tableWidget_duplicata.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_duplicata)
        self.tabWidget.addTab(self.tab_duplicatas, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1294, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuTabelas = QtWidgets.QMenu(self.menubar)
        self.menuTabelas.setObjectName("menuTabelas")
        self.menuTemas = QtWidgets.QMenu(self.menubar)
        self.menuTemas.setObjectName("menuTemas")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelecionar_banco_de_dados = QtWidgets.QAction(MainWindow)
        self.actionSelecionar_banco_de_dados.setObjectName("actionSelecionar_banco_de_dados")
        self.actionAtualizar_banco_de_dados = QtWidgets.QAction(MainWindow)
        self.actionAtualizar_banco_de_dados.setObjectName("actionAtualizar_banco_de_dados")
        self.actionFornecedores = QtWidgets.QAction(MainWindow)
        self.actionFornecedores.setObjectName("actionFornecedores")
        self.actionEmpresas = QtWidgets.QAction(MainWindow)
        self.actionEmpresas.setObjectName("actionEmpresas")
        self.actionTransportadoras = QtWidgets.QAction(MainWindow)
        self.actionTransportadoras.setObjectName("actionTransportadoras")
        self.actionProdutos = QtWidgets.QAction(MainWindow)
        self.actionProdutos.setObjectName("actionProdutos")
        self.actionFusion_Dark = QtWidgets.QAction(MainWindow)
        self.actionFusion_Dark.setObjectName("actionFusion_Dark")
        self.actionFusion_White = QtWidgets.QAction(MainWindow)
        self.actionFusion_White.setObjectName("actionFusion_White")
        self.actionWindows_Dark = QtWidgets.QAction(MainWindow)
        self.actionWindows_Dark.setObjectName("actionWindows_Dark")
        self.actionWindows_White = QtWidgets.QAction(MainWindow)
        self.actionWindows_White.setObjectName("actionWindows_White")
        self.actionSelecionar_pasta_com_XML = QtWidgets.QAction(MainWindow)
        self.actionSelecionar_pasta_com_XML.setObjectName("actionSelecionar_pasta_com_XML")
        self.actionAutor = QtWidgets.QAction(MainWindow)
        self.actionAutor.setObjectName("actionAutor")
        self.actionEscolher_arquivo_do_banco_de_dados = QtWidgets.QAction(MainWindow)
        self.actionEscolher_arquivo_do_banco_de_dados.setObjectName("actionEscolher_arquivo_do_banco_de_dados")
        self.actionAtualizar_Tabelas = QtWidgets.QAction(MainWindow)
        self.actionAtualizar_Tabelas.setObjectName("actionAtualizar_Tabelas")
        self.actionAvisos = QtWidgets.QAction(MainWindow)
        self.actionAvisos.setObjectName("actionAvisos")
        self.menuArquivo.addAction(self.actionSelecionar_pasta_com_XML)
        self.menuArquivo.addAction(self.actionAtualizar_banco_de_dados)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionEscolher_arquivo_do_banco_de_dados)
        self.menuArquivo.addAction(self.actionAtualizar_Tabelas)
        self.menuTabelas.addAction(self.actionFornecedores)
        self.menuTabelas.addAction(self.actionEmpresas)
        self.menuTabelas.addAction(self.actionTransportadoras)
        self.menuTabelas.addAction(self.actionProdutos)
        self.menuTabelas.addSeparator()
        self.menuTabelas.addAction(self.actionAvisos)
        self.menuTemas.addAction(self.actionFusion_Dark)
        self.menuTemas.addAction(self.actionFusion_White)
        self.menuSobre.addAction(self.actionAutor)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuTabelas.menuAction())
        self.menubar.addAction(self.menuTemas.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.horizontalGroupBox_2.setTitle(_translate("MainWindow", "Filtro"))
        self.horizontalGroupBox_3.setTitle(_translate("MainWindow", "Filtro de texto"))
        self.label_8.setText(_translate("MainWindow", "Colunas"))
        self.label_9.setText(_translate("MainWindow", "Texto"))
        self.horizontalGroupBox_4.setTitle(_translate("MainWindow", "Filtro de data"))
        self.label_14.setText(_translate("MainWindow", "Coluna"))
        self.label_10.setText(_translate("MainWindow", "Data Inicial"))
        self.dateEdit_NF_inicial.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.label_11.setText(_translate("MainWindow", "Até"))
        self.label_12.setText(_translate("MainWindow", "Data Final"))
        self.dateEdit_NF_final.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.pushButton_nf_limpar_filtro.setText(_translate("MainWindow", "Limpar Filtros"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_notas_fiscais), _translate("MainWindow", "Notas Fiscais"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "Filtro"))
        self.horizontalGroupBox1.setTitle(_translate("MainWindow", "Filtro de texto"))
        self.label.setText(_translate("MainWindow", "Colunas"))
        self.label_2.setText(_translate("MainWindow", "Texto"))
        self.horizontalGroupBox2.setTitle(_translate("MainWindow", "Filtro de data"))
        self.label_13.setText(_translate("MainWindow", "Coluna"))
        self.label_5.setText(_translate("MainWindow", "Data Inicial"))
        self.dateEdit_duplicata_inicial.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.label_6.setText(_translate("MainWindow", "Até"))
        self.label_7.setText(_translate("MainWindow", "Data Final"))
        self.dateEdit_duplicata_final.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.pushButton_duplicata_limpar_filtro.setText(_translate("MainWindow", "Limpar Filtros"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_duplicatas), _translate("MainWindow", "Duplicatas"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuTabelas.setTitle(_translate("MainWindow", "Tabelas"))
        self.menuTemas.setTitle(_translate("MainWindow", "Temas"))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre"))
        self.actionSelecionar_banco_de_dados.setText(_translate("MainWindow", "Selecionar banco de dados"))
        self.actionAtualizar_banco_de_dados.setText(_translate("MainWindow", "Atualizar banco de dados"))
        self.actionFornecedores.setText(_translate("MainWindow", "Fornecedores"))
        self.actionEmpresas.setText(_translate("MainWindow", "Empresas"))
        self.actionTransportadoras.setText(_translate("MainWindow", "Transportadoras"))
        self.actionProdutos.setText(_translate("MainWindow", "Produtos"))
        self.actionFusion_Dark.setText(_translate("MainWindow", "Fusion Dark"))
        self.actionFusion_White.setText(_translate("MainWindow", "Fusion White"))
        self.actionWindows_Dark.setText(_translate("MainWindow", "Windows Dark"))
        self.actionWindows_White.setText(_translate("MainWindow", "Windows White"))
        self.actionSelecionar_pasta_com_XML.setText(_translate("MainWindow", "Selecionar pasta com XML"))
        self.actionAutor.setText(_translate("MainWindow", "Autor"))
        self.actionEscolher_arquivo_do_banco_de_dados.setText(_translate("MainWindow", "Escolher arquivo do banco de dados"))
        self.actionAtualizar_Tabelas.setText(_translate("MainWindow", "Atualizar Tabelas"))
        self.actionAvisos.setText(_translate("MainWindow", "Avisos"))
